-- =============================================================================
-- DigitalFix - datos de prueba del microservicio de USUARIOS
-- =============================================================================
--
-- CONECTARSE COMO:  DFX_USUARIOS
--
--   sqlplus DFX_USUARIOS/digitalfix@//localhost:1521/XEPDB1 @seed-usuarios.sql
--
-- O abrirlo tal cual en SQL Developer / DBeaver con esa conexion y ejecutarlo
-- completo (F5 en SQL Developer, "Ejecutar script" en DBeaver).
--
-- ANTES: ms-digitalfix-usuarios tiene que haber arrancado al menos una vez, para
-- que Flyway haya creado COMPANIA y APP_USER. Si sale ORA-00942 es eso.
--
-- QUE DEJA CARGADO
--   20 empresas de mantencion electrica
--   4 usuarios por empresa, uno por cada rol del caso
--   1 usuario desactivado, para poder probar que el sistema lo rechaza
--
-- ES IDEMPOTENTE: se puede correr las veces que haga falta. Una empresa se
-- reconoce por su nombre ignorando acentos y un usuario por su AZURE_OID, asi
-- que volver a ejecutarlo no duplica nada ni pisa lo que ya existe.
-- =============================================================================

SET SERVEROUTPUT ON
SET DEFINE OFF

-- -----------------------------------------------------------------------------
-- PASO 1. Sincronizar el contador de las claves primarias.
--
-- Las migraciones V2 y V3 insertan filas con ID explicito (1, 2, 3, 4) en una
-- columna GENERATED BY DEFAULT AS IDENTITY. Oracle NO adelanta el contador
-- cuando el ID viene dado, asi que el proximo INSERT automatico intentaria usar
-- el 1 y reventaria con ORA-00001.
--
-- Esto lo reposiciona en el maximo actual + 1. Si tu version de Oracle no
-- soporta la clausula, el bloque lo ignora y sigue.
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE compania MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    DBMS_OUTPUT.PUT_LINE('Contador de COMPANIA sincronizado.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Aviso: no pude sincronizar el contador de COMPANIA (' ||
                             SQLCODE || '). Sigo igual.');
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE app_user MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))';
    DBMS_OUTPUT.PUT_LINE('Contador de APP_USER sincronizado.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Aviso: no pude sincronizar el contador de APP_USER (' ||
                             SQLCODE || '). Sigo igual.');
END;
/

-- -----------------------------------------------------------------------------
-- PASO 2. Empresas y usuarios.
-- -----------------------------------------------------------------------------
DECLARE
    TYPE t_lista IS TABLE OF VARCHAR2(100);

    -- 20 empresas de mantencion electrica, que es la red que describe el caso.
    -- Las tres primeras coinciden con las que ya trae la migracion V3: se
    -- reconocen y se reutilizan en vez de duplicarse.
    v_empresas t_lista := t_lista(
        'ElectroRed Valparaiso',
        'Mantenciones Alta Tension S.A.',
        'Servicios Electricos PyME',
        'Tableros y Control Quilpue',
        'Energia Segura Vina del Mar',
        'Montajes Electricos San Antonio',
        'Redes y Subestaciones Limache',
        'Ingenieria Electrica Casablanca',
        'Mantencion Industrial Concon',
        'Grupo Electrogeno Villa Alemana',
        'Instalaciones Los Andes',
        'Potencia y Control Rancagua',
        'Electricidad Integral Santiago Sur',
        'Servicios AT Maipu',
        'Redes Electricas Curico',
        'Mantenimiento Preventivo Talca',
        'Alta Tension Chillan',
        'Electro Austral Concepcion',
        'Servicios Energeticos Temuco',
        'Mantencion Electrica Puerto Montt'
    );

    v_roles t_lista := t_lista('ADMIN', 'SUPERVISOR', 'CLIENTE', 'AUDITOR');

    v_empresa_id      NUMBER;
    v_oid             VARCHAR2(50);
    v_empresas_nuevas NUMBER := 0;
    v_usuarios_nuevos NUMBER := 0;
    v_total_emp       NUMBER := 0;
    v_total_usu       NUMBER := 0;

    -- Compara nombres ignorando acentos y mayusculas. Sin esto, 'ElectroRed
    -- Valparaiso' y 'ElectroRed Valparaiso' con tilde se verian como dos
    -- empresas distintas y tendriamos la misma empresa dos veces.
    FUNCTION plano(p_texto IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN UPPER(TRIM(TRANSLATE(p_texto,
                                    'ÁÉÍÓÚÜÑáéíóúüñ',
                                    'AEIOUUNaeiouun')));
    END;

BEGIN
    FOR i IN 1 .. v_empresas.COUNT LOOP

        -- ------------------------------------------------------- la empresa
        BEGIN
            SELECT id INTO v_empresa_id
              FROM compania
             WHERE plano(nombre) = plano(v_empresas(i))
               AND ROWNUM = 1;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO compania (nombre)
                     VALUES (v_empresas(i))
                  RETURNING id INTO v_empresa_id;
                v_empresas_nuevas := v_empresas_nuevas + 1;
        END;

        -- -------------------------------------------------- un usuario por rol
        FOR r IN 1 .. v_roles.COUNT LOOP
            v_oid := 'seed-emp' || LPAD(i, 2, '0') || '-' || LOWER(v_roles(r));

            BEGIN
                INSERT INTO app_user (azure_oid, email, nombre, rol, activo, compania_id)
                VALUES (
                    v_oid,
                    LOWER(v_roles(r)) || '.emp' || LPAD(i, 2, '0') || '@digitalfix.cl',
                    INITCAP(LOWER(v_roles(r))) || ' de ' || v_empresas(i),
                    v_roles(r),
                    1,
                    v_empresa_id
                );
                v_usuarios_nuevos := v_usuarios_nuevos + 1;
            EXCEPTION
                WHEN DUP_VAL_ON_INDEX THEN
                    NULL;   -- ya existia: el AZURE_OID es unico
            END;
        END LOOP;

    END LOOP;

    -- ------------------------------------ un usuario desactivado, para probar
    BEGIN
        SELECT id INTO v_empresa_id
          FROM compania
         WHERE plano(nombre) = plano(v_empresas(1))
           AND ROWNUM = 1;

        INSERT INTO app_user (azure_oid, email, nombre, rol, activo, compania_id)
        VALUES ('seed-emp01-desvinculado',
                'desvinculado.emp01@digitalfix.cl',
                'Tecnico desvinculado',
                'SUPERVISOR',
                0,
                v_empresa_id);
        v_usuarios_nuevos := v_usuarios_nuevos + 1;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN NULL;
        WHEN NO_DATA_FOUND   THEN NULL;
    END;

    COMMIT;

    SELECT COUNT(*) INTO v_total_emp FROM compania;
    SELECT COUNT(*) INTO v_total_usu FROM app_user;

    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Empresas nuevas en esta corrida : ' || v_empresas_nuevas);
    DBMS_OUTPUT.PUT_LINE('Usuarios nuevos en esta corrida : ' || v_usuarios_nuevos);
    DBMS_OUTPUT.PUT_LINE('Total de empresas               : ' || v_total_emp);
    DBMS_OUTPUT.PUT_LINE('Total de usuarios               : ' || v_total_usu);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
END;
/

-- -----------------------------------------------------------------------------
-- PASO 3. Comprobacion a simple vista.
-- -----------------------------------------------------------------------------
SELECT c.id,
       c.nombre,
       COUNT(u.id)                                        AS usuarios,
       SUM(CASE WHEN u.activo = 0 THEN 1 ELSE 0 END)      AS desactivados
  FROM compania c
  LEFT JOIN app_user u ON u.compania_id = c.id
 GROUP BY c.id, c.nombre
 ORDER BY c.id;

-- Los identificadores que sirven para probar el BFF en modo desarrollo:
--   X-Dev-Oid: seed-emp01-admin        X-Dev-Company-Id: (el id de la empresa 1)
--   X-Dev-Oid: seed-emp02-supervisor   X-Dev-Company-Id: (el id de la empresa 2)
SELECT azure_oid, rol, compania_id, activo
  FROM app_user
 WHERE azure_oid LIKE 'seed-emp0%'
 ORDER BY compania_id, rol;
